language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.4
  - php: 5.6
  - php: 7.0
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.0
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
  global:
  - secure: Ds3TVudLdJgIxZOZubVA0tL9JRg0bzppwH0Kl5rqoY/I8xVOtaMgQH1dmxvp6SXl3pmHupb2qrwRk1LKnm4KJiCnqcWs9WFukDd7wWj2XpuehbDRIBgum4yOZz6ofATyIgWO7uDZDoMrjNhnHuGsDwCP05w+rWhSzb3Bik0a0yyOXMKFaGFZ7buiIiAvWioX++fHZZQCMtDs3bLFGKS7B6SU5Whom5fBZhwObbw9MSnPQfKLEReSEtCAzHbpphPn9uyayjcn4Z10E2jIzbJKGPHpWZrd9TmmYVsQt8CZchH33O63VpvlsA0+FgemZzQ2biS2MExmxLG+ooQnN9ffrbM6U/JDlO1zZK6fXfoq5/tnNrLcI8h5DUkWrMC5Z/CwiNOPuZW1gkDnmFzMGbPsuxY7Sr+HipybvdnTFBuS85MuhnxcxoFss5L+h+H404bkO95I26vAliKro55utE1y4hAGbw1+o+DRmU+Cvn/9CARMnhd6+I1P+g74Nf7AZd3z8Lis3N//Tb8E0SvQaZAl3UBZRirQSbB7/IY325/qqv/w+ufWZgD7EVZ8t0itFPxs/hzDKsXCpKDWlWBurcp/Lmf1Gs2kKZps9AUaEfom98xELBZon7memqSb/Qu8hOCGWKqkV+LeikDcov5s5cCvo2+mVV4Dba6or7h1vq/5HQU=
  - secure: TYR8gwivFjIkEtMU7R9nXOZNpTQlVqcdyr2+ctrrwRkXVfIz+/G7Y/Cx2BuYugAdC1Z887ona8UWOkAOAK3wzLCr5Swkee+XFcjOsUkg6js/KBDpwWX0op1oUeqov97sLpREw+ski8RoID27+QwwZ47XG/FZ00dpKtdacxBSO37n7r+REd8nzzM8nH52t2jAr3uRcFi1+j/TTQV1Or5opQ3qDqCp/OQVb6lJ5QDRy5v6/ryX7x56KFAVYkULhu9a8pr8FUVRB9vFig4lvOLLgZgodeFUHo8RZPSfp+tHlZRHB/cIvCQK9o1IcrFGDxM3rZ9JXTkz5/amqY9sWP+hnkd9niKAW88dyV20wQTtuXBm9kNQnWJnXULWzdU5hdwrcL8IPufO0FgHnLelWM2AqJZhP9OXEwAlAb0+HGV3yIXTBFZFmKiDAcQjuGIT5Fcft+ZSwVMVQe+yi1v8jD2aJMBHA7N+7XzXOlbYCLPjfIs+TrzSZEd3XsfdjyDuWg7ID+xxXLCpQ/XmVVBurLs1IP9GAC8t8RTboOpyJVgmcsSLXHRrqdWmurgVz+Gk0G88GZMYo8qoHaMVGC4sdgVTUaAM9if/HuVScvO8qOEDm7JWWkcdbZVsB36m6hDnY9DpjEeyrF6MsOmwtBLAn1h6/X7/bWVTn8opowQR051jU18=
  - secure: DgaGmdqFpTnvR4Zw9nGDlrN3BCSz4bfZ5PemzK9eQlwL/rAH3J9SKsZGv0kqAhJ05ZeRw+35vrA3Ks6hhdqDohj1eUamb7K4VVRA1aEPtfDbNnd/tHmYlzWhPiSMYLZmTuyplZEYLR/MDXR5h3ZORmjCynpb0z4MOjRAOZK2wKjwJHo/Cwvp4VpHixVKjUzvsUzI4aSmHgvI4/kBBz5e5+0/ljnwJPbX2w7WKFzAxn1UkGwTqMcW+yspV47doh5HPuL3NKEEhzyKRtfmp5R+GWjvJFI5kbR6h5m9fs+voWp2ymmUYQeH2DobqvfLcXC9NTl4lIffMky6y3YAT5ut+G3CFU0tpDNyQr2pApk/beyPMJhegOSFu0t/Rnyyt6+2hHHm9HBFngVq/Blw4jjjBfgqm/2+ntwG9adxRXvP+Zik8u0lb1idNFCEdiN3RwPQVViTvSXeKilJaOpvdBR8GblC0P/fut9ULW9vtAHc9z6B9BM8/iSL47gVivHVDG44TNolw132UbzwP99rMlde4/F46LAVj/4munu2GV6ebknVKKsdVVqWuyG4dVppTCelRYtJz+D/e5kh1xe3g1ACpyQt+XfcyBZgysbGRFQQ5/r8djk3EDQj7y5uZiprch/zKALPnVgC5Hx57LeqYav2XJoV5s1EFH3mh6AgFNPiQd4=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
notifications:
  slack:
    secure: ZKqUPaWMRpOJ1f5W+/8JuGhmdRmTz75TgYDSGA7wwEIky5fP1ReWV3si2yypec2F16umxtRs4jROUvOcdSrQsiDJP3tShmKOq13FAgzJmllFlUsl8qKy9KGjWs1+tqqGIgsmXFcO4VodvZCND4B/4s4S6VeKujaz00P+LanNNbszFZY6c1cPTWhywrTsRH5SHXJusYB9jYZ3XZxcPMmVdrG1wPEVyP9gHK4NSHEKwfgHuaV1+zR8e7OLJeaVFjLjLoElI9Xq6UL5D3Z1dtRTsJk8Zb7hBfXZFHp8qt7jDMYndsBy0iq0CAdc5ngSpgqmpc7pB1g9tpVb/br6Nn3wvKpiPDtaxFhj6/RXxrlnwOUoOpOOHO2SUKYWlg3oje++1PmoFfbFKurb6jU85BraDFchjZoROn40DunzfExXTB4W9H/K691QcgaQXJfdrRi4eQ0TTzAkrOfj/6ZzsW27dnnD2AfnW1ud4RNLsZaIh35szUd/v71k41sxk6dgPC1NDVtXhJPSue88Q0C8i1l1uuO9AbQCSGOnuiI+2a76eQwrpzpLc4j00vL37NtfUNmSyzaYZ8hYyPswkXEx+jco2d4yPoFxP2x7n8ZWX0kroRXAdHrknWh9EWlKHUXtMYd5kLycrjy0I9hmLl41YdNm9GBqHAZEKhiXvjqLMQOvqHA=
