language: php
sudo: false
php:
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - env: MAGENTO_VERSION=magento-ce-1.9.1.1
  - env: MAGENTO_VERSION=magento-ce-1.9.1.0
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.2
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.1
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.0
  - php: 5.6
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_UpdateScripts
  - secure: HAiMfbvrCRc1UYJN8s8Su+F7neiDJQuyLYZoNCTbpW8kydMxalT/sKvjpCVLQB5DrW70W9WkDOF0WGlnpdPyKngru1aY9BjCoQZJl5V99tREXu5QG7Y7L7RVhhs+Vq3/8Uu5DsYCt894zUkjnlIcZ2B5PAHr9a7x0upYB943kudD9+aKSFjNk/rHrPSZVSzSaBvQXrGUGg+7J1vkHDiprQeETESWEyC2CHdKzKUsyTV9yG/YaHxrfl38vGENSJG7eSM6ZSNWQvkljq/oelCvxey8oiblgWhZSwHCmM/gvWGoTGgBj5TETX1//RMwuc+RwKxcZiVQrHlvbf2N67pPORIaFjGdlLTxuHYAQFo1wyCNzJLlrfw+Itn/02uRZ2yj/QKakeq2aHg0OIM+BIYfUVTwnkI7g66IZWEmADdyziobNcCUZxPSIdg5ZP0LTeJO18u1OFRw9hcOhllEE8Eg5C04oywhzHGMsuAGCZZlnzbQN8Yt38HW5ZnoNPOzR4QLsD3S5m13x0uQZsSugbcf+QhbnA30w/c9SNi/3cexdvfKyvkNequny5yjyCWeHhYsJW2dEUn6sUqSS7J2D0S9BZPPzcUKReYHw9/GqqECyRhYrxi+DTdLYKt2Ret9beWdQNK5XCCJms9PUedaRbUyC0xeBEf92WC4YDTVO5iCfkc=
  - secure: FX1UXTNM5aqLDt2ii5Z4ZYWYdIptYVZgBP+o4MicX/TIL4sR7a6wMSpx4xNO8nmbGkYNVDaGFueKKadtKbHLjfTuXqADMZ49m2Dhm9NgHxtl95YFF4V+tY9tf2DGoMGehpPgnehUrxzPWXxVpBPS00ejV7rlxygoVof1/Ki3BuhmA/KFHV5crrVFsK3fD79Dh2SnhXm7EXmp2T5xjtGwe1rjrHGTlXZKPiehpVAHZ+C1QS3GXWYIuPCP0RrnNyuKrvo+orGChoqUOp9+VCXPgn+R2ByJoH1Fi2+kx98ydfDP9ysjh9noXEI8IfxcRgkmp3Xof0gPybAfYbEoXqdx3KfBdt2qyaT0pQLbE+KOb6W7FFdUp7Cr8B4zmglQtFAYDxNOUtp6t5FEhdf39IZ0k+rezQ/5z59k+caxw7G9AYAcyuh+PxERKcmurgw1rMXPIQ19dIy4VL+Dc48libLDm+4cqbJ/9B8UJe8fe7oMhkCn7pAIG5tV0tkikX7sCKJyH6lWQJaot63qsKSvsmWba7+b2NLCAVBEqIMX3ovDVdjngWvIdeHlM1wdL2GZYu5MY9DvAXPDmwQD5mltjQofYAsJlmIcz784f8Jh9/2+cGhhjmhdSjH5cI86H3FkGxrxlLOv58pqiLvYwsIexgHqbEFeMY3ul9FpPZukJ7i22zI=
  - secure: OuPbvP27f9daVd3P2duVYIdwk1CG7AwCh6Fj7QbGytVhRX/oYwvzgIBMwdSPqmMnovoZR+ykvdsuGKm8sboBqm9Zf2KoKSGJCmCttUmOxOB1D2tphCNUOZo8XY5yFA9G5A5HuHeDw5qlny3q5MRU+7ekamNwEWHW1yqQaLTO1+QwCnALgkpD+vPElkmko7JQ1yjA5OqdOuTZ+XMW+seM0lKH/hd/L4+qCkKl1oeey8JiJ4Wz4jcKosSMHoUBQ93+GXRJXyHBIfOyajXrP1asWoF4JE5IseJYeu8FnWqhB88+rAnfUdjV9FwG4hcnoJHxFEkUM0cRe6v7Jjpu/K59tp6A8SepMrARH4FpEqZ6dN7T+nCYoabrPaRBrx9MUHqrYBbdhQo2llOGJ6q219E3xvr4t6reXRgqKbwSi4iC5uR20S9oYXyzLAzl95e2sZXE2hcbwzKKGs0f7MObPe5Y6+SsO0xKN2KmxkYFPRVCY2CGVWOqey0HcZ27BpTCF8kOd5MQyXO+R46nK/fVvObX4d1FlLZPlgj6MW8k9q8knz7vYhU+0DUbUbgog/bT0Z/Uad5Ws/FV5d0xTlJd3eiSNSBo1d10Zp/S/uCQG/NcX+3Xl9JoZyjX4hPtogIaRxHZPom3rPt08XobEDjv6WSniN9jw0SMZwvuTMpEx440zuY=
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
before_script:
- composer self-update
- composer install --prefer-source
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: Dgyd4nnpGtdAvHwfbofkf+We/yENucnw7t5xZ4HddmG8gj0KNuRuSlDIkw4L6s+vlxpH1F9yqj/hpRgFARUo9oAxXM7mxPq+VfodkMet6LCasqYaszSHEmUrEh2M/44DNJfKw6fLCJzvFtG78DLNKgAjRa39TchiACnCuP48hUbrTA4tbudLeENFhIY8tLhNfp+T1Gx00sdlfO5toI6hG0Fp8a9SRhKwFKiopKeH7KJ4RqxDNyesKQV8hRtVYlRv7MCLctM2JO+Ls7OC+g33VPFzmsyLbLt7CRUZ5idYpPRgJbX9V6jtDV47Y/8OqSy3xVpLHzgd4T2G/HNrrIk/Sy6+7scwYvWCZ1CZ4s1hTtmj/8KfzztqzNdC6kqvzoxdLWbn9XL462dXqFM9DHNeiz7UCZFtnk6yMS4tsJkmpUh2KlXrrvqqWI8zZ2PpUaBIz1oCTShgk2jLJo+kmDKpvrYGeQC8kQexI2vtvYSoa0b/+z/duRHZar20Sglk0Umu0+apQKdth8j/SxOBKh3eM/g1MVXQ4fN4/GRfoqWlXoW7jVZUpbqijTvYddtDzfs6zdYRewFI6FC9fxvDrnTIz4AOjCFps/aAmPtucXI1PlF77kS3fFy35gePJsFCm+90HsTr0XWFcRGi6oBDdzBZb90nTLiLE7HFHAU/5lj0Kos=
notifications:
  slack:
    secure: jnKVUiBhMqpEMKrHCVBjc1kZX4BY3FHgQuPvoyHorvRSyPpZHqL5FxQtIuc3tu9QCzZmtvQLGbfCQ6e6X/FI5anmSzI8LVnqG1qrC1KpTH/lKmf4YZvZ6JCPNkbQD4wA1E/OrDSbUcjBwSd416I/9EFXt6vG8CsooBFGtoeuxK6KOIpvp3dJP/pd0Rj+fEIq19hmFFO+CKZEkBRxsJw/BI3nD8lv1YhtP1imUCrRcaZLhr24g/lBYNEOMhR26TvyW8UcfhIJow2r02exyPacr8Cv9GCOn5GwJhKjrKRisHsVi1J/+niUhtmYJgmQ2lsS4mZdIOsyos9eTNRXv+qR61k9GxJwr2lMi3tDOVwj3qxujljcSmFxMKZ/5mRlXqkJqWhGJa793zOBQ5eN67jtUrPSafsiSls2q92s8fX58rc/QZwMRORCyAXpMTt1IJDsZYBSyeZvQMzdckwKtXCi3wZ74nNB0LgXbXn+mJazNR4ZF3AX+w7VHHliv9KUc1EE6ZONixd1Zy7e59Cdv+H1yyPQ8FzZOT1Llxo3npXuoXPSUndDewgyiAE3/fPzQPCysKAQbZD5G2PrJKjLAS/i0RFAsRg9RoRwIg/C8E7eaJjPhDnI2rN/rDyR1e7bDcKTiB+6fz/isYkPnnqr7602TmOKq0AVJjp59K4IC2ghgRU=
