language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_UpdateScripts
  - secure: WCXGk49jcieXCsgXw/Dl6MPJc6Hq3I9SDdzl950ySvh8pEAfvsuyVRg66kK0WAKtUYhMUlKClHtLhtSqv8ohL5dRvTOFhrxqzFjypVsfA5PupCH4RRD+aKviS4lZFpeDoQsr5GEJ0Qkg//t2GRAO0oW3WK14lXJPg0jHzawpa2AZWgF1tPn0/SmL7LndNmFysyfHrDzhxiqhM7PegOETQ3jpSq8o0QTTj7AgcnWD0Hs2HThS0yT93Kmj1/pPtwKLpjRKV+9Z6XLaXYb4o7YNc+qcvnPkOu1wI0GyD5Bb2UBRaKS4NzgmfwX2RHO0C8tmMba8yemu5h59AoLqa/h8kyIQmhPfRN70Bc5D6oao6xez5WZ0+SQOaDECNT4XqAQ+mfTd9XXY1b6KfSGwZlqXW/ZT4WqiRfDEahdTTC0CjJpUvY07l0IylRGwmRX18V4Uy0S60SBgl9JQWyLm4YzNumNZEQDpDZD5SgfcV/p6AtA5eH6aNXoe3LtwivcfD/0Cea0tRjexEPQPmTiRN/Mhw+b6m4oR2zO9MUuMOG4iQXKycQ+gX8sSS/unerOU7nqPitIgEeY5EVKsSUwmcSRQXsYKIw1ztVi65vyCWppVYIeViKY4IJbb3GUpksjPcmbipP2Yo4AYQ1zO0A0Ty1s2jpNq2R5vtFW1VRD9a7DTdTg=
  - secure: bKxpVONRdJndIs912QzIMVaLw/WUFs9EXL7es+pxtt93On6vx7Fmbb2E5BtW7KTZcWVk2WO4nU+RpYkmfUH23+XX3SSpFbVE5m0yo7Hhxq2QfldOUbY4XJhhqOR9kpXz15bENDHeSJ2Be5v7UsD4XAqVLgYJoJbX/zAW+ZZ31fPtvYktTDLcPY1nlI9Mcu87DWJxBxhar8vW1Xpia3tnPRp6NgsLFo9wTH6+K3nKstxU8KmHKkg9bDohYDhGxO/z3bz1sGp0+oF1g9YJJhYEjOF+wCJ8BC6FslL2FVeotaHCef2bB5HnSJpCW4LIsxgpKMar1gGtA0FX7NNopVpVm0XLuNarYNXBSTELEzb/DiaS3GfQxsNTwwD0/uSMkvRr2LiQkUZeDpk15j8QbQhMsPmRd9woYWaK9remIPb2zzYPWF3ZTB6pMb7N1PzmTa/SdjHh0oKuk5P0DePvNNbCBnBNhqHx8P1J1LYSm4v09OB3mrhQd1q71/Bk32XQDYhjygQ6x0v0lPLJ8zGt+wViIfKDJ0mjW1QNpFqtrj1O6uqetIeZtMNC7qCKkBSzfAiockgwuXEMpu69IkfiftwA8oD1WgMLQx0lQaStrN4rb45vZ4b0XLZRlMldq7U9AnbGdAo5onsGZLD87xWjuFkKLaqK5NhRDqCwTbLNo3fuG/E=
  - secure: OSd9GI8Mt3Ed0rfYYxbsn8h8YJnIMSNl2DB99DqMAuGJiUXI4F9pE++xwlKi9HLSTEuv7jKvpiahMDLv0WaLXjeuW3NDtObgkikioYx+JwqYNNsjetaEfFMLa8BbLBuilwwJFPE6XjqMTNcvZCPCSMbxZWyL3/A1u4F7QYXGASeVR5FpPOILI0VPol05XYrWwOmL1+i3XN5InChp7GFwddRILoJ0omAROE4r0Rw7yWWX+O9PEZwbj3WQJNdDvzL5eNccJ9Rejx7K8mECiFgbio75g7YlUpXNDaGfAcMh42bf7EoUUnGWbrSqYMv304vQ48EqVqjQspVIDfNkOy+NuMsn7HuP85XZGDgDLPnBnkJgdmlicjCGXDUuoX9D2tqwaWiinn3RJQMOqlVL74Spq9rGgBOh+TkHnCS8YrRkt01QJo0MnsmlyygmXliuGA7ufjNyHxwjiZPhwtgtHhrkzvQLvyRftGmC3inS21QsI0PSjrCFsB6xapNYHgbm0Cw1q/UXZBEl8bav11ESawYp6ojQ4tE0KpVJolx0xKWkTL433j4EwFzWx3aMJ3VNwY/KqHzM4t1vcOHNWI3WMdjXwWMkW3xGp2DlpyxmFEyUGBSrirmwr7gXHCJRTjV1Q/Rbv5Z0lavsiNA6PXP3wP7qhGtkzLUm2csSp9XNAzkA7s0=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: ZXA5qt/8MKx5CZLUvtD2EjJge/BGjcLFbVKQd2XASS3CRMoBH1W3HicHk9xFwWeMgaEDSkNf1Wn6PcV7NVIgVVa4zuJaPb/qZOKrAAmPk7AiF1pVUfRI262lpG5Mp8M2tITBRia35w01oOBnl12UY/lc7ND54lmEmd31b2wDuz/s4nwbHeJMnS/e+iFRzS7IWppsokU5BuJWoUgl+POwxqUO4BzG0+gcO0NAsr+P2kKrI0x0Xb9fCKB+lxfaALyjhI0h9kffdJmC5LQYeZ4RCbDdNnDMYFz4O02cqoGKHh/jHpktzYw/JD+q6YpDJ2lSYb2GDZEWrp65BWaB/V/ndj33iYajDcUX6xXBPDksw3DBcYlOTr2DRvtLwilKy3gM/Gybu6gxSkoHpbL/LG+TILQd9ftKNwKfX+UErvJCP0Xn7HMkc5v6wslxq+zXChv0AqgrJSx8RieVnr8GGj+MalbyZalsnQaReFl5Q+5ldoq5QHF/L+sqGAiaW51x60phK4OKCtNDJjEGsw7fCLIM9+m1A+87kgXRMVjA3hOoSXczVfW0kwfNQNEwPWWHAhIzjgq7Oa/WTwMT2Vv8wwjkzHOOJFVQZ8mX9pLQvyKw3NMtt3B1Diqj3CW4JB4ero4qXSMqr84phj9RbC27QLJRXuadBPjnVOm3FpGJMcqLe5M=
notifications:
  slack:
    secure: MnI61GwQIq34cotH8F2Pi2I/EhZrysAfjJaGYA4XWIPq0Xn9fAnzWBBdRaKBembeN9jJ+iYGbpFDM28mXw307/FGMPh5j3hHOIEm6KL38vpfLzuDSKHnEAKFsPVKDYg/vhjuoPAQ5KJvIxs4M0N0OGxyUWK5YX1WsRKGVoO3L2GxwAC8ZQTDxX4A1S45t5fIaHOru5yQj2KBnoDV8eeCdkzb0acB1P25jQUniMXobrR5fuqyu+95wJOZfLG/X3ZHpNucXLOxaoYPm+iqwLs5q2bi8q6spFPXPpIiFOH8G6BXbUfrk6Ah+9uxFnJWN39L1JsSfV+3aaSkgf2SuyIvy2Obwd06PnSCK3EwZupMoM1Q3j4UuhvcS1fQUCz5IfD+QI3a0Q0zZklODQyb21pcVY6sCwydiixu70nm4Q8v/2nHwqS/cCg+bYriZhRrZJF5Nule/su64/RM9tXmyrauH0Q/CheVS13UbsBIztXnA8McfGlehc7SJ+NSoxaJtGByqQeYSgyOL6YAluK05h6LCHd9V/7b6dIghCfx5NrKoIEfQvFT4nfOM9FQ0KZadT4bjXGuT34mzJ+is8viAVI+UlwShjORinn7FvBSggWEJMI0yn6NIjMcF8sIHgfECx0U1mOXIDlYHupIseF5AeMnyoFY0r7yExcdswJYjiHsdlA=
