language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.4
  - php: 5.6
  - php: 7.0
  - php: hhvm
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
  - MAGENTO_VERSION=magento-ce-1.6.2.0
  global:
  - secure: lcFjrxaXQziLYVkVsl+2Y4qX8y2ry5Q5B99QGaiMdx1wwCyaXUCukNbYE30FydihAKtmNw/N4fNO66u8kaY1C5KHetYU2wFkbdQshHonQarsx3lERJ+JWw16HNZXuOhYLtnRZMdUc0PFYEwFWlkwBVxFMMNyZPMSfbjJj8bsmpGG1pcQVcVKBGCkGIxBbmw/8sPHBitnud221vZsE/g25/258wKRBQmM2M793K5V1N49llaHvhax3x5LY5LsApVrWSzhId78rBgDXvzG/EzL/fspkWxTPfSv8es9CywJYLiCl/1c9BbeOFlqqV3gWpxNwkvgbUGwnBz+Spi4YPx9rE4SGiSdBfF9wwkpXF5xgqYYoX03y5nTC7upkXf8ZoBvsZhrxGtMfdzBbUljD4FhWGUEvcYb/MU+4KnLrwiYKvRSvZr2ZtSYiL/EnBKKZgg58eioUtx3ZNMZ4TQNkiozlheWpgX0zJOAR8HlaVdfGxoNtHGSqR0kr05qhHryDshku3Ptr+zWfCxi1YPUAp5wg39INd6FxzbaXTjrToN3bUZeGMjeMS1TiKs+j1WLWvXwoawxXDvniLjMeWgTFWZq/2Ig4cOUs5CEgTsU27QfLo11eoEwdutetz49t/qDns5/WtvW7uYY3snwfSai24oEa/ygaLzMeqJmwtepTkNjm7g=
  - secure: mtcTzINQzRoPdO+DJe1P1VYql7AVi/GsryZAOh/bV+eXl5oJgA7YaqfCX/LLlqjHwASOWwALnoJ95Jq7GNGuZp6ILc6KMLSObBSRnauj+W+/JEFP9eWX/ACNMXDUAgs6FLRS/iRVr76AaixnvH4QoUBSBCexoya4ceIuqgT9jgGFme0hRoAFqZX04oyKT7B7/D5O8Nfitl3NjixecxGj3k0ncZDDgaBz8KDvwgdwC5xNVH/b+6ac6gAP3TPaaEAqj2vDdyeEkwnrhBVsOY4BLPUIl86PupqCQxVfNDiyE5ByNSDsRQWiyplzSrwpEKtYQrao80AkB2JDJ7yQKnOz3QVeyvWPf0bT0C3HesMKt79yCOgDYubUuRoOxKVg+SxgthQiiV1KbJSAE0UVahs6CdcYP+I2Yfyo25VynZTafT8YQc2NRVdhj1grEQ7N+yYKxBX6HEy9HbOpIs/YuaD2dURPe5XMwDzNsdeQjE/urPATSFaIhoLFpmPMVnmc02ONa0eeM2PvCgDNpL796GGn0X2qKdGVEp6sEO8BBgXG7hZ9zKtxZAqlUwufjxTIJrXY4LoEssAIK0J2bHnN1xqNhL3vbVDxXtgmhK5P9L8blfZFNtpi/Q6ZARJSClbKO/9i2toGdsyKFaURAl6A+8y4ZiehAEoB/zITjCsUgy0dRQ0=
  - secure: mDnD8i2VVxvBQcSsQ9H3/SGlakbgnH+xa4jr0+0qFTT8r0YXY6IHpZEjWnH9a7gQJ9kl28vzCgoawFqbQe+j9OKizJemGSFrtGj60Sswe46Q0uaZ7v82FJgHVkd/NuD7DaGgSETV7fBGswPZm8ClSHvGlrhKx55QnIlh//1dN4XsnFG4tYm5YZ88VuvxlyGKfYX+wHBlQ7UUOLs9AqxsD9xy7sXlibtr1Fj/Oru6cE1n6BR80UBQIpIojC15V5CsqoRJjhmmz2Y3yHCXbVhIDa0w+y7bgJely7X0mqCByZMlTZB0jL2noumtA9z+5tSDJ/Oe3c7izwqz9GZHPoZPHcp0UJmmbOUtX9Z812nhh3imHVcbT0FX3ETbBpdAMODyJitWRCgGvlkZ0VNXj3t78mLgWNW38xvEXczlDSwybivyM9KjEZW2cLRT8I3K/68EfPxj2CfKBi6UhapIvxFO8T4mPGrRFOSgGfekksi2IojnZWRzz7dJR4TuZ54IgRrtFWV1+swNWFs/2yfefForwxfDURSN2RyJ2278HbxRdfaRJBKEefea4qpsLOyrcmb/7IqflgMFVF0OCPmuBj+zXHp6rWfJ+NHauYJaCn2huMfu3QUiMX/i9lCiFcJQsCodZIZ5zmGM+hkFLYy1jnB4FiX5NVNh7S3hQxyxeLUnfRE=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
notifications:
  slack:
    secure: jdBYBWY123O0/EbyGFVTJf5Z3HYqxOvFzMAwWSKQMWr4bX3JOvHap+57gn/3w16/0m9VaVMUMDcBGEAQvPatze9E4ok2lPA67bBL99+g5kbGjTyh013wJuNVuznd+BqjA8RG+vWNBLft3rZGrXQ+X6IW8mw3GWDu2liUbCw6AyOekd3be/T3v7s7OyB1t3SRR1D0raOiJWAmXQ8gN17bWTgI1cuyhdYrbnlprFMI8ppLajWbrDsqMdF/w/QuGAwAwqB/1+5BXNXu0A9XtlwsulMfVvt+LQGMhzSUOQaPHg0A8HW16Tf48u2R1tXfUKcOGwpT3N6/sjve7RPEvjgQx5SRcdT6ydJpIkvdRvFZzco3wn6gXV+vU/N2r6NsDlnLE9GNseLUEeZTshBjI58oid6cV79ibYQgsZrTPtIcWdeBFUcxNGFHXfvtbfMNnKP9LBzDLOJ0SwoUUQCnUsxT2Gbob+RXRn8M8sXfsR4fQOUgmoJNFLOb9O3D6S2ZPtr0homkOsmLnLJQTYNGF9P379qEFihBbFEPUl/WgGHg2jqDFRX+RJAMIIC5onJUBkVCvPrPz9pp7fXzJ8bTi3CUgsnhjpwD7RP/NSbw30wLWUc2VUqxfk1Uv3RbAXOGwDI15nf33DjvkbI1eyITXfK3RrzS/jJRtSRfxSAfRfJwQ9g=
