language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.6
  - php: 7.0
  - php: hhvm
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
  - MAGENTO_VERSION=magento-ce-1.6.2.0
  global:
  - secure: BeNgtsa/Qc41MoDtgB8WrdCIZWXwUhuyOs9PvlTYd/4Svep/lhrBJe66r0z8kLijPZNXnGzrYS15pJiAeT16ZiEU+IurUZG1PTKxGJXarumg+gEdKFoCXOjk0/6MjdR7nNQG6xLjYtTB3J99uOCDQTs+WoVhOcG49jG/8VUKPtay/pANpS2Ggo6Jlgn50r+hTs6LNvdJjescZWYl5XChaS+WRqkKjL/Ws3p4zpdqolUJj5ZbtUQm+Z41ULnvGJNL9P/CGtJvti2TME84Ju4Feqm3dZoBLENBp6yJ8w2/j/QC1K2Qx4DRfCKdGLRJvf+OGFXZWNuibHWq9AGlnMwGc4BAwW5DEspVZqMMmF+FEYt0rqATpGwE/WQsGXvrnR89RsrgSBY3TdqV8jIm0juAeN0XQohGUHqmuMPpJOYbXz6yFYmRzliEboLZEti+nvYh3X08Fvk3NwU8wwdfPpZO4XoXLgRyfx77RvdAc65FmcFr88nIdiBzwkKQ6eLedTFiXRWa+PbrGSrJBmAHsDDV0AJ4ZpXzG54cIbTUK7Y83ubfj/sjLChaQTP4hIqTu1KGpONRsWlnuDfifLiW0srKeogbZIQPNz4LZW8gAmiZj8Gy/Gf/ianZLOOIAkQVZjaHsVpdhdDISxT9utqs/Ic3CNlzIah1B+G7bvIjQ9GB0GU=
  - secure: UL3e7V1nF9NX1K62WYgNYWqolfvvmM1dQh2K0HIvifM8f4i7A9tpjfskab57wNH8jKBsvu1vaDWPODELDZUr5yODiVxTcJW3BSBtlA0cknzfbPK245BdFrCTBypL5OxrtOFin22ZtRj29jyt2KRy2mGsHq/0NwBM7wbyl/K1PaVy1B6+Kp/4s5lvecOqMsrYUfjPCLsaTepn0fhEu/PvGg3h36QMdszVNEmHNbnBgp1DOSCoKLUeyKZotB5PxXSVoSgOGK+PewZ8WJBBAT7h2m0HvG2fApliW9mz2kvOSsXnAH8Gsty+mFPz1CRWVw48gJT9A3MQhrAvzAoThpYFaF1a6RKWZOaiX4j/taRfaOYImDDG3mvAgi3mYnH6aaTWssJ0BRBdyIMAmBJwIeY1el/yrovbNZiwEmo2M7jH8XS+z5k0OOluf20stRpcg1C52YNqCHxMPhFa58JAbl4tXHTg0RlymMesL21xwRP4vzyqxkuKHkOuVl1XWpxNPjhl0puBDyjuZtckBomBFauE0P/FlnurKvmmthsyqj/WhOb8fNSxnnBR8mdVWEzqFF0NNPkYuaFV1iyP41UccaVv2bjZpGwwcgkViD/1ztXX+hwjq5C0OL0he1CfN/dvOHUKYhmm4CTwtdm7FOHz+QcSR66/OPKbXqDZ5pwApsJaetQ=
  - secure: k1PCF27aFU0EcpAtdZ6hiX1i/h+BjNND9YapDX9gWaDG3lQz7Ag0oDSlZM8QLZhGajwg25BDXTN8nMfcKO4g6zpUy8lYTaL8hKcDAcMvj2bxrJJ2AqWCMEtkv5p/wsGuXXCqTCxdnMDNGB51E6diX6ACOEc9xaWSVo5mNL5Uj+7pkdsrROjE0ewG6A5pWaTugFRWtVUAfhgkyWcxz3d78Zyzz6McAn1xmdbpCDyjazRpCOZ2C2OoyhEsuEqBSstAfG45qAOmCtv9bfU7lxtU3Ckkk1hj9KhasBGGy6e1pxHseqjJg1IRO/TR8u5s4VszxxVBUHKQVAVdOenqogFraBEiaZCkpqGaJbSbMHD2C3kG904W8iixfzlkmqRJyU10s0yNEW7KZRTieQjZw2RZDT2eOtGgby6CDY0rtuEAPWu2nQ9sZEfW1DN2UEquL1LOrzEV6r6bYqVWobI8XvMV9d00Sln++Oa7YS4urf90YFdU4dn0YuyNEhcTtalcrixSt7GyiXk9SMT0JavWIZLyC50nW2iZMO+hixqA/tFiw0dVrk/UWw1bl5HsfdRWxtKNciZgJNbK9uCYptzRfzHF4VOdDWaklkuFv+yk7CXVQXivWc+T5EW3JWn/vfRNvTCqatP3FN3iZgIQT7FmKqVAs15LeaxqB/+U/i4IQ8YaUs4=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/testing/setup.sh
  | bash
notifications:
  slack:
    secure: cE6zm4Gf0jyx+TsbwMofPGQQCOWRGVH0+6j9+bOaFe4R/fi0u/aVcTpbl1peT8QMhehJavfIlcdrhz0sAYiFqx8HXtP4WIigJT1KzONNAHqaOTnR09QZPGYgxdmlngnKTDOltw247o3URLnvETjW8hlIFRJJWKgmd3KPg1uglpKOJ1vDToWbfxfiCuRJURoMkBkTvsgc/zw9UAAbHVXnGXoqmbM+8sn8hcYxFzPfaq/IGlFeXZJEa570NJ1uD8snckU4ycwQib6+w8v2X0Bvs9Qp8XUQPaeNTfglNd1jo1hEAx5N+uNUXCscp2ccwQ5FMssthjY2oA33d2uAYZBwe8FMs7zvRWELwzQgMbibrZM46z2WFGWDgaGqFtFck9WTM8Kbvx0KJmWF0pKktiVLBE+ogJP0zHbH1nbg8g8brpxJ+H4mVUi5N2ugYKgPnT9PhgwI/XXQU0sx3QKRz9cts8P0EVGw2wBK2CyojWSjqM8siYL6ap/JVHgaj59tj8bUs51Muat/5OwEDvnzqUlyst8REP/zOfTO4YBCmJ1UyoD+uB0EYi7S+LZRWXKkR6IQL+0ZIZ/tIPVxFk4OznZ/ouf9nCKmy1tzWX97bbxXzy45fFgqqdaz/w7EjSBFoCa8CWjHwnovwfQ0uiJK7YPC2M60jwcKtOoIEIqmE4GxcCs=
